name: GitHubBuild

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: php7.4 $(which composer) validate

    - name: setup templates_c
      run: mkdir templates_c || true

    - name: touch config.local.php
      run: touch config.local.php && php -v

    - name: Install dependencies
      run: php7.4 $(which composer) install --prefer-dist -n

    - name: Build/test
      run: php7.4 $(which composer) build

    - name: setup coveralls
      run: mkdir -p build/logs || true

    - name: Coveralls
      run: vendor/bin/coveralls ./clover.xml || true
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
